library(tidyverse)
library(readxl)
library(RColorBrewer)
library(igraph)
library(ggraph)
library(ggthemes)
library(jtools)

# Theme for plots
theme_set(theme_base() + theme_apa())

# Data from readers ------------------------------------------------------------
data = read_excel('data.xlsx') %>%
  mutate(word_length = str_length(clicked)) # Count word length

# Generate Figure 1
figura1 = data %>%
  select(position, correct) %>%
  group_by(position) %>%
  summarize(P_correct = mean(correct),
            SE = sd(correct)/sqrt(n()),
            ymin = P_correct - (1.96 * SE),
            ymax = P_correct + (1.96 * SE)) %>%
  ggplot(aes(position, P_correct, ymin = ymin, ymax = ymax)) +
  geom_smooth(se = F, linetype = 2, size = .5, color = 'gray') +
  geom_point() +
  geom_errorbar(width = .05) +
  ylim(c(0, 1)) +
  scale_color_brewer(palette = 'Dark2') +
  xlab('Posição da palavra no grupo') +
  ylab('Probabilidade de rememoração')

# Save Figure 1
ggsave('figura1.png', figura1, 'png', width = 16, height = 9, units = 'cm')

# Simulation -------------------------------------------------------------------

# Check distribution of word length and compares with a normal distribution
data %>%
  mutate(norm = round(rnorm(3900, 7.862503, 2.247305))) %>%
  ggplot(aes(word_length)) +
  geom_density(adjust = 2) +
  geom_density(aes(norm), adjust = 2, color = 'red')

# Function to create random non-words with length based on real distribution
random_non_word = function() {
  paste(sample(letters, round(rnorm(1, 7.862503, 2.247305))), collapse = '')
}

# Function to generate a list with a given number of random non-words
random_word_list = function(level) {
  paste(sapply(1:level, function(w) {
    random_non_word()
  }), collapse = ' ')
}

# Function to simulation addition of word in memory and spread activation
add_and_spread = function(list_size) {
  # Generate list of random non-words
  word_list = random_word_list(list_size)
  # Separate words
  vertices = word_list %>% str_split(' ') %>% unlist()
  # Create empy graph
  g = make_empty_graph(directed = F) 
  
  # Iterate over the vertices
  for (i in 1:length(vertices)) {
    # Add a vertex to the graph
    g = g %>%
      add_vertices(1, attr = list(label = vertices[i],
                                  length = vertices[i] %>% str_length(),
                                  activation = 1))
    
    # Set the edges to the graph
    if (i > 1) {
      g = g %>%
        # add_edges(c(i-1, i)) # line configuration
        # add_edges(c(rbind((i-1):1, rep(i, i-1)))) # clique configuration
        add_edges(c(i-1, i, 1, i)) #ring configuration
    }
    
    # ring configuration
    if (i > 3) {
      g = g %>%
        delete_edges(paste0(i-1, '|', '1'))
    }
    
    o = 1
    
    # Spread activation starting from last word
    # while (length(neighborhood(g, o, i)[[1]]) < gorder(g)) {
    #   g = g %>%
    #     set_vertex_attr('activation', neighborhood(g, o, i)[[1]],
    #                     neighborhood(g, o, i)[[1]]$activation + 1/o)
    # 
    #   o = o + 1
    # }
    
    # Spread activation starting from first word
    while (length(neighborhood(g, o, 1)[[1]]) < gorder(g)) {
      g = g %>%
        set_vertex_attr('activation', neighborhood(g, o, 1)[[1]],
                        neighborhood(g, o, 1)[[1]]$activation + 1/o)

      o = o + 1
    }
    
    # Normalize the activation
    V(g)$activation = V(g)$activation/sum(V(g)$activation)
    # Set the names of the vertices as the order they entered the graph
    V(g)$name = V(g) %>% as.numeric()
  }
  
  # Return the graph object
  g
}

# Create simulation with 6 (non-)words
g = add_and_spread(6)

# Generate Figure 2c
# Obs: Figure 2a and 2b were generated by changing the appropriate lines in the
# function add_and_spread() (line and clique configurations)
figura2c = g %>%
  ggraph('kk') +
  geom_edge_link() +
  geom_node_point(shape = 21, size = 8, fill = 'white', color = 'black') +
  geom_node_text(aes(label = round(activation, 2)), size = 2) +
  geom_node_label(aes(label = name), nudge_y = .15, size = 2) +
  xlab('') +
  ylab('') +
  expand_limits(x = c(-1.1, 1))

# Save Figure 2
ggsave('figura2.png', figura2c, 'png', width = 5.5, height = 9, units = 'cm')

# Generate Figure 4
# Obs: Figure 3 was generated by changing the appropriate lines in the function 
# add_and_spread() (Spread activation starting from last word)
figura4 = data %>%
  select(position, correct) %>%
  group_by(position) %>%
  summarize(P_correct = mean(correct),
            SE = sd(correct)/sqrt(n()),
            ymin = P_correct - (1.96 * SE),
            ymax = P_correct + (1.96 * SE)) %>%
  mutate(type = 'Observado') %>%
  bind_rows(tibble(position = V(g) %>% as.numeric(), 
                   P_correct = V(g)$activation,
                   type = 'Simulação')) %>%
  ggplot(aes(position, P_correct, ymin = ymin, ymax = ymax, group = type)) +
  geom_errorbar(aes(color = type), width = .05) + 
  geom_smooth(linetype = 2, size = .5, color = 'gray') +
  geom_point(aes(shape = type, color = type)) +
  scale_color_brewer(palette = 'Dark2') +
  xlab('Posição da palavra no grupo') +
  ylab('Probabilidade de rememoração') +
  scale_y_continuous(sec.axis = sec_axis(trans = ~.*1, 
                                         name = 'Ativação final no modelo'))

# Save Figure 4
ggsave('figura4.png',
       figura4,
       device = 'png',
       width = 16,
       height = 9,
       units = 'cm')
